language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - pycodestyle --first ttn
  - pycodestyle --first utils
  - pytest test_*.py

before_deploy:
  - python setup.py sdist
  - python setup.py bdist_wheel --universal

deploy:
  provider: pypi
  user: ttnci
  password:
      secure: NTOQGwbSsMt2FDrOlaWoOrW7yKwxeEsqqViNtKog0Oo/iePS6VXn/7qIuhNjl74rN5DtX4JJZ/mYxw7mCkSfbxG0vtyVV4O3vRZQ88xnDVnNX9zL4OZahDeLesUWt1ZaHh29skZOVa8a2v6mRL8Ozs7TZHX2Ze47h7N6MOizdHAhipnEQR5Fi4V5rUzt8rkWJysSC5X6VwrVs152Q5MTAKRhRhzVP0wfpprh/lopqSD/IB6H1w97uIJEtN6sDzM09RmwNirsShld1Te3BVpLN+9tDecs/9mTK0csD3wwf4+1beY8RY0SFCBe9gR1efzhTaL6LqxsE3P6Q0+0Xd1fltZUcW6MvarKZEoZgGcgZYtvQbrv5QiifkfSxDZNTY2Em2CKL39Z95oEGRaOQ55Z8T8Ip2HJf0KU61YkursY/j1ggwNxsqYSHVOKaZxuWJjdtPxVI1NAeenLGxoYV585FDU6NxVipG/WogjdYn/YP82u9VSvA5c7xW1Cqsy0R/Sct8A5Qn6xOvb6eHrb7SKWYtVtnj9gO+HLmUo0ENbTR24ZGHCuQtXgmWX2X2cZ96ADidQP9T+4mPleE2tASRXNSwCvxB1BqPVFi2HJ8dXzdvs0xHQ/n0lvoUHsjhvZ63x+f+VAWumGwWYbEyFc5UfkOyFVC7T4kS8jQVIrBToGngw=
  server: https://pypi.python.org/pypi
  branch: master
  tags: true
