language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"

sudo: required

env:
  global:
    - TWINE_USERNAME=ttnci
    
services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - pycodestyle --first ttn
  - pycodestyle --first utils
  - pytest test_*.py
  - pip install twine
  - python setup.py sdist bdist_wheel
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload dist/*
    fi
