language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - pycodestyle --first ttn
  - pycodestyle --first utils
  - pytest test_*.py

before_deploy:
  - python setup.py sdist
  - python setup.py bdist_wheel --universal

deploy:
  provider: pypi
  user: ttnci
  password:
      secure: wVYjBWUf+7xcLEWUufgDmfoMrwKGFRWsEAJ+EiCXECgKzbkdIZYjA5zQCrIxpjl8Yu4ybMAGY+tc9lg9scY2OKXontMqjJZZDO/v75H02GHDhusKs1OMbPIhVBYpiPTLGiFg7yBD2HCf812H4fS3JwkxWFv2S9Rtng4257omm1DYPvr9BM0yC4wd2yQ3ulo+PKsaIxCWg7XXEmKBGZ1irG6s5yu1a08ZyGUsk9cfwkqrfuoSqnlFiShtmSBlM7O4xEWflXw5qDjAP7BS80/HvCkYgFRWiK75//SR1zfQ4QaOmS8ZSiXHY4m59WeKMb75MHti7sxanGnpNyE32LFrx8hdcmjuKHN1HeASjlY/tdyumGTau1A40u9RDzGsIwkOtoSAcCAWN5nT7uOjScGXHoUAoFWdw8Fa130PvvAchibPRrz1H40eYoLc5mB8szked7ymXk2v8Lug87GMI/HiwdzA56jg2sBvVVJOMONf3OFH+hnqsz37A8nED6PIINV2qSayfV6XAt9j+xF87VG6tjw4usIUUzOMj/QOq4zOeDFYe5mUxKT866AaMOokQML9r7mga3Y/jMNN+hq1l666zwbHEIJ6zOUfVQD/FYKwNOcyLHff1FTnLg0fEqwzPIQH/mF1+EGngwYz+rJMgoaSy6a2785Ah/hVA3u4FQEzEwc=
  server: https://pypi.python.org/pypi
  branch: master
  tags: true
