language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - pycodestyle --first ttn
  - pycodestyle --first utils
  - pytest test_*.py

before_deploy:
  - python setup.py sdist
  - python setup.py bdist_wheel --universal

deploy:
  provider: pypi
  user: ttnci
  password:
      secure: Gna241/npBYQwObDEwZTMbp1Jwipv/nRE+agUaV0LkgWdaGgKpA+nn4ZKnh+MuUxbBid/6p62DYkRhWvJD/rgicQuhNrVaNrNDWAl8ev2ouEecC+Aqo+XMjijfUpaGcJqCPLfoqo6p9RXiurSy9Ca0E/KmwhzcognDxdSGxrClmW3TOuF09ktYfuiD4vZNlWB0gW2WdZfuCem+ivYtfMCdd9KoqlC1fyr0HLsdG9fZ8fu7z+qTVgN1SDpuhg29xBJ7JW1nqruNwsSC2lrBHCa6OZzmn5ZJURvmPHZ4vE6v83JoE2zMrnN1ds+/jmyZplLZqnZ8n2SglYT5LNZ74I+QnqVUWiAFccR3x+TW9u8t8G+3FQea95Lwi7zS/+xSi0X85iRvEuhQDFKI0kdyhVaquxyoGbuJf2aWRFGIra+7sYM3pUHDcatfjEtt8FzRjxq7/wiekCgOGIhvj/dX88UlFMLXDQ34+22tQvORucBVt2Qk5ho2wZQ7qxop8pwsnWfdB/3M+bqj1tqKGPCwiVwRhI9uVW78EEfwVhB48aSWCs0vCni1jaYoowcnj+lms9g9oxpfSOJv/tcZxsoQ3wp7Ctb9ctqIKQcOJPhOCW7yAdvhMrMCPW/Dw396FyQ455XWgP7JPlYAuZ77GQryiJFfurVPAqc42hwSpUxF4GDFo=
  server: https://pypi.python.org/pypi
  branch: master
  tags: true
