language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - pycodestyle --first ttn
  - pycodestyle --first utils
  - pytest test_*.py

before_deploy:
  - python setup.py sdist
  - python setup.py bdist_wheel --universal

deploy:
  provider: pypi
  user: ttnci
  password:
      secure: E7w/gsi1hf7SjkmDX1NV6cyXqG/bS/x+ikcNY79Nh2X8cehVkxa75aglEh8b0SeRSRocgSmF2sqsQvLNMqGQ0T4iCLhV0W7+HVndyOUlNZabMafUW2+bFde18ZahnP6miO+EEliKYoVkDUmkkFmPva9AM741MNge4oHX24dDYXmzTkP4vsyiAa0Y1krdk9gAkAp4ZbLVoJKRKCcq4Vehvk3HVqKptnmlAM8GqT6oYNHrr1ZPNb9TAcGlscHHvsjBlKflqrXaNRn4CA7p4pX2x8cLpIq32EPkRIdc2wohe2/ZarJ5jKvOXnSSNSbSh7OBWIm5bDI8StR4UOeEVyy5Bo/1juSPblLTTjEbV5Bg34vgvWgYeNgYrKynXw8CzuVASIRprB0eUqsWB0jg/S16xtwkTE92SOi8418GL/Atae0nNNS3cmFfrwBNtVx6GsxYdVWzpsIN31fB4R0Wg+j5gxUZEmQ9fHK4MHBKNBSi/Xhph9cjs6Yyu237Gze86jROaoA+jQGrhaJP4WqOTc6dgC35ZZW2btlKUQ+EZMbbJh2KlhEZylgN/P+7lw2V+zHLicfCUrivjEJI2P/fqaQs7YNfXkwOSjp2x0sJRuPHdEnYgsyM7ETMOHCnDaC6Kyob1XamFgxLVQ4C5S0f0HusYETeTP9NU5ZXgKQ
  branch: master
  tags: true
